### ISSUE TITLE
onnx flask有版本限制吗？

### ISSUE THREAD

**Issue by wikipedia2008** [ZhangGe6/onnx-modifier#1]
> python3.8 app.py
 * Serving Flask app 'app' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
127.0.0.1 - - [09/May/2022 16:22:44] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [09/May/2022 16:22:44] "GET /static/view-grapher.css HTTP/1.1" 304 -
127.0.0.1 - - [09/May/2022 16:22:44] "GET /static/view-sidebar.css HTTP/1.1" 304 -
127.0.0.1 - - [09/May/2022 16:22:44] "GET /static/sweetalert.css HTTP/1.1" 304 -
127.0.0.1 - - [09/May/2022 16:22:44] "GET /static/sweetalert.min.js HTTP/1.1" 304 -
127.0.0.1 - - [09/May/2022 16:22:44] "GET /static/dagre.js HTTP/1.1" 304 -
127.0.0.1 - - [09/May/2022 16:22:44] "GET /static/base.js HTTP/1.1" 304 -
127.0.0.1 - - [09/May/2022 16:22:44] "GET /static/text.js HTTP/1.1" 304 -
127.0.0.1 - - [09/May/2022 16:22:44] "GET /static/json.js HTTP/1.1" 304 -
127.0.0.1 - - [09/May/2022 16:22:44] "GET /static/xml.js HTTP/1.1" 304 -
127.0.0.1 - - [09/May/2022 16:22:44] "GET /static/python.js HTTP/1.1" 304 -
127.0.0.1 - - [09/May/2022 16:22:44] "GET /static/protobuf.js HTTP/1.1" 304 -
127.0.0.1 - - [09/May/2022 16:22:44] "GET /static/flatbuffers.js HTTP/1.1" 304 -
127.0.0.1 - - [09/May/2022 16:22:44] "GET /static/zip.js HTTP/1.1" 304 -
127.0.0.1 - - [09/May/2022 16:22:44] "GET /static/gzip.js HTTP/1.1" 304 -
127.0.0.1 - - [09/May/2022 16:22:44] "GET /static/tar.js HTTP/1.1" 304 -
127.0.0.1 - - [09/May/2022 16:22:44] "GET /static/view-grapher.js HTTP/1.1" 304 -
127.0.0.1 - - [09/May/2022 16:22:44] "GET /static/view-sidebar.js HTTP/1.1" 304 -
127.0.0.1 - - [09/May/2022 16:22:44] "GET /static/view.js HTTP/1.1" 304 -
127.0.0.1 - - [09/May/2022 16:22:44] "GET /static/index.js HTTP/1.1" 304 -
127.0.0.1 - - [09/May/2022 16:22:44] "GET /static/logo.svg HTTP/1.1" 304 -
127.0.0.1 - - [09/May/2022 16:22:45] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [09/May/2022 16:22:50] "GET /static/onnx.js HTTP/1.1" 304 -
127.0.0.1 - - [09/May/2022 16:22:50] "GET /static/onnx-proto.js HTTP/1.1" 304 -
127.0.0.1 - - [09/May/2022 16:22:51] "GET /static/onnx-metadata.json HTTP/1.1" 304 -
[2022-05-09 16:22:51,596] ERROR in app: Exception on /open_model [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 15, in open_model
    onnx_modifier = onnxModifier.from_name_stream(onnx_file.filename, onnx_file.stream)
  File "/Users/dengxuezheng/BeKe/tf/onnx/onnx-modifier/onnx_modifier.py", line 26, in from_name_stream
    model_proto = onnx.load_model(stream, onnx.ModelProto)
  File "/Users/dengxuezheng/Library/Python/3.8/lib/python/site-packages/onnx/__init__.py", line 124, in load_model
    model_filepath = _get_file_path(f)
  File "/Users/dengxuezheng/Library/Python/3.8/lib/python/site-packages/onnx/__init__.py", line 54, in _get_file_path
    return os.path.abspath(f.name)
  File "/usr/local/Cellar/python@3.8/3.8.13_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/posixpath.py", line 374, in abspath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not int
127.0.0.1 - - [09/May/2022 16:22:51] "POST /open_model HTTP/1.1" 500 -
[2022-05-09 16:24:02,033] ERROR in app: Exception on /download [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 26, in modify_and_download_model
    onnx_modifier.reload()   # allow for downloading for multiple times
NameError: name 'onnx_modifier' is not defined
127.0.0.1 - - [09/May/2022 16:24:02] "POST /download HTTP/1.1" 500 -

执行python3.8 app.py 出错，大神帮忙看看

**Comment by jf99** [comment]
I don't know what the Chinese means, but I have the same errors by just loading and downloading an arbitrary ONNX model.
```
$ python app.py 
 * Serving Flask app 'app' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
[2022-05-09 14:12:58,782] ERROR in app: Exception on /open_model [POST]
Traceback (most recent call last):
  File "/home/jf99/projects/onnx-modifier/venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jf99/projects/onnx-modifier/venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jf99/projects/onnx-modifier/venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jf99/projects/onnx-modifier/venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 15, in open_model
    onnx_modifier = onnxModifier.from_name_stream(onnx_file.filename, onnx_file.stream)
  File "/home/jf99/projects/onnx-modifier/onnx_modifier.py", line 26, in from_name_stream
    model_proto = onnx.load_model(stream, onnx.ModelProto)
  File "/home/jf99/projects/onnx-modifier/venv/lib/python3.8/site-packages/onnx/__init__.py", line 124, in load_model
    model_filepath = _get_file_path(f)
  File "/home/jf99/projects/onnx-modifier/venv/lib/python3.8/site-packages/onnx/__init__.py", line 54, in _get_file_path
    return os.path.abspath(f.name)
  File "/usr/lib/python3.8/posixpath.py", line 374, in abspath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not int
127.0.0.1 - - [09/May/2022 14:12:58] "POST /open_model HTTP/1.1" 500 -
127.0.0.1 - - [09/May/2022 14:12:58] "GET /static/onnx.js HTTP/1.1" 304 -
127.0.0.1 - - [09/May/2022 14:12:58] "GET /static/onnx-proto.js HTTP/1.1" 304 -
127.0.0.1 - - [09/May/2022 14:12:59] "GET /static/onnx-metadata.json HTTP/1.1" 304 -
[2022-05-09 14:13:01,622] ERROR in app: Exception on /download [POST]
Traceback (most recent call last):
  File "/home/jf99/projects/onnx-modifier/venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jf99/projects/onnx-modifier/venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jf99/projects/onnx-modifier/venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jf99/projects/onnx-modifier/venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 25, in modify_and_download_model
    onnx_modifier.reload()   # allow for downloading for multiple times
NameError: name 'onnx_modifier' is not defined
127.0.0.1 - - [09/May/2022 14:13:01] "POST /download HTTP/1.1" 500 -
```

**Comment by ZhangGe6** [comment]
感谢反馈！该问题不是由于flask版本导致的，可以通过将`onnx_modifier.py`中的
```python
model_proto = onnx.load_model(stream, onnx.ModelProto)
````
修改为
```python
model_proto = onnx.load_model(stream, onnx.ModelProto, load_external_data=False)
```
解决。仓库文件也已同步更新。

---

以下是一个简要的解释~：

- ONNX的API [onnx.load_model()](https://github.com/onnx/onnx/blob/main/onnx/__init__.py#L102) 默认`load_external_data=True`，读取[external data](https://github.com/onnx/onnx/pull/678) （用于适配大于2G的模型文件），读取路径是从传入的文件流中解析出的，要用到文件流的`.name`属性。
- 在`onnx-modifier`中，模型文件是以 [tempfile.SpooledTemporaryFile](https://docs.python.org/3/library/tempfile.html#tempfile.SpooledTemporaryFile) 格式 返回给后端的。如果使用Windows做后端，会在根目录的`TMP`建立一个以随机字符串命名的临时文件，并将该文件的路径保存到`.name`属性，此时`.name`作为文件路径是合法的；但是在Unix环境下，不会建立保存这个临时文件的文件夹（或建立后立即删除），`.name`属性就仅仅是一个随机字符串，作为文件路径是非法的，导致了这个issue提到的问题。
- 所以解决方案是，显式地指定不去读取 external data。因为`onnx-modifier`是用于模型图结构的，所以功能应该不会受影响。

这个工具之前一直是在Windows环境下开发和测试的，看到这个issue后，我在Linux系统测试了一下，这才发现了这个问题。再次感谢反馈^^

**Comment by ZhangGe6** [comment]
@wikipedia2008 感谢反馈！该问题不是由于flask版本导致的，可以通过将`onnx_modifier.py`中的
```python
model_proto = onnx.load_model(stream, onnx.ModelProto)
````
修改为
```python
model_proto = onnx.load_model(stream, onnx.ModelProto, load_external_data=False)
```
解决。仓库文件也已同步更新。

---

以下是一个简要的解释~：

- ONNX的API [onnx.load_model()](https://github.com/onnx/onnx/blob/main/onnx/__init__.py#L102) 默认`load_external_data=True`，读取[external data](https://github.com/onnx/onnx/pull/678) （用于适配大于2G的模型文件），读取路径是从传入的文件流中解析出的，要用到文件流的`.name`属性。
- 在`onnx-modifier`中，模型文件是以 [tempfile.SpooledTemporaryFile](https://docs.python.org/3/library/tempfile.html#tempfile.SpooledTemporaryFile) 格式 返回给后端的。如果使用Windows做后端，会在根目录的`TMP`建立一个以随机字符串命名的临时文件，并将该文件的路径保存到`.name`属性，此时`.name`作为文件路径是合法的；但是在Unix环境下，不会建立保存这个临时文件的文件夹（或建立后立即删除），`.name`属性就仅仅是一个随机字符串，作为文件路径是非法的，导致了这个issue提到的问题。
- 所以解决方案是，显式地指定不去读取 external data。因为`onnx-modifier`是用于模型图结构的，所以功能应该不会受影响。

这个工具之前一直是在Windows环境下开发和测试的，看到这个issue后，我在Linux系统测试了一下，这才发现了这个问题。再次感谢反馈^^

**Comment by ZhangGe6** [comment]
@jf99 Thanks for reporting! The error can be solved be changing 
```python
model_proto = onnx.load_model(stream, onnx.ModelProto)
```
to 
```python
model_proto = onnx.load_model(stream, onnx.ModelProto, load_external_data=False)
```
in `onnx_modifier.py`. It is a Unix platform compatible problem. And the repo has been updated as well.

Fell free to comment if any errors still exist^^

**Comment by jf99** [comment]
Thanks @ZhangGe6, your fix works for me!
