### ISSUE TITLE
Unable to download model after changes

### ISSUE THREAD

**Issue by TravisHaran** [ZhangGe6/onnx-modifier#11]
@ZhangGe6 This tool is exactly what i was looking for but unfortunately after I make my changes on the development server I get the error that on line 27 of app.py, that onnx_modifier is not defined.

Traceback (most recent call last):
  File "/home/travis/p38_venv/lib/python3.8/site-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/travis/p38_venv/lib/python3.8/site-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/home/travis/p38_venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/travis/p38_venv/lib/python3.8/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/travis/p38_venv/lib/python3.8/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/travis/p38_venv/lib/python3.8/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/travis/memryx_dev/onnx-modifier/app.py", line 27, in modify_and_download_model
    onnx_modifier.reload()   # allow downloading for multiple times
NameError: name 'onnx_modifier' is not defined

**Comment by ZhangGe6** [comment]
Sorry for the late response. This problem can be caused by several reasons, one of which is (currently) unsupported editing operations.

So **would you like to share your editing operations and expected editing effects?** It will help to fix the issue.
- A screenshot of the model part you edit, or the ONNX model file (if possible) is recommended to illustrate the editing operation.

**Comment by ZhangGe6** [comment]
I am going to close the issue due to inactivity.
