### ISSUE TITLE
Cannot download modified model

### ISSUE THREAD

**Issue by turneram** [ZhangGe6/onnx-modifier#116]
**What do you want**
To trim an onnx model down to the first layer

**What did you do**
Using either the .exe on windows or the app.py script on linux. 
Remove nodes with children -> add output -> click download

**What do you see**
Error happens!
Please check the log and create an issue on https://github.com/ZhangGe6/onnx-modifier

**Additional context (optional)**
flaskwebgui - [INFO] - 127.0.0.1 - - [12/Nov/2024 16:45:33] "GET //flaskwebgui-keep-server-alive HTTP/1.1" 200 -
flaskwebgui - [ERROR] - Exception on /download [POST]
Traceback (most recent call last):
  File "flask\app.py", line 2529, in wsgi_app
  File "flask\app.py", line 1825, in full_dispatch_request
  File "flask\app.py", line 1823, in full_dispatch_request
  File "flask\app.py", line 1799, in dispatch_request
  File "app.py", line 34, in modify_and_download_model
  File "onnx_modifier.py", line 470, in modify
  File "onnx_modifier.py", line 454, in post_process
  File "onnx_modifier.py", line 366, in toposort
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
  File "onnx_modifier.py", line 358, in get_hierarchy_level
  File "onnx_modifier.py", line 358, in <listcomp>
...
RecursionError: maximum recursion depth exceeded

**Comment by ZhangGe6** [comment]
@turneram Thanks for the feedback! Can you share the ONNX file to help debug?

**Comment by ZhangGe6** [comment]
Closing due to inactivity. Feel free to reopen it when necessary.
