### ISSUE TITLE
在多输出模型中删除多余输出节点报错：AttributeError: module 'onnx' has no attribute 'shape_inference'

### ISSUE THREAD

**Issue by XiaotaoChen** [ZhangGe6/onnx-modifier#34]
### 问题
原始onnx模型存在多余输出节点，原始模型输出如下图1所示，希望将输出名称为Yaw，220， 221之外的所有节点都删除。故将其余输出节点在gemm部分删除，删除成功后输出节点如下图2所示，但点击download后报错如图3所示。

**原始输出节点-图1**
<img width="1659" alt="image" src="https://user-images.githubusercontent.com/23189018/215314809-1cc01218-5632-4002-9977-9493d2b0b19f.png">
**删除后输出节点-图2**
<img width="724" alt="image" src="https://user-images.githubusercontent.com/23189018/215314990-6d72db71-3fed-4121-b946-1c06951300b6.png">
**报错现象-图3**
<img width="552" alt="image" src="https://user-images.githubusercontent.com/23189018/215315050-20fa4542-df49-4952-b990-cba23ccc7a6a.png">

**具体报错log**
```shell
127.0.0.1 - - [29/Jan/2023 16:31:52] "POST /open_model HTTP/1.1" 200 -
[2023-01-29 16:38:03,331] ERROR in app: Exception on /download [POST]
Traceback (most recent call last):
  File "/Users/cxt/miniconda3/envs/pytorch1.9/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/cxt/miniconda3/envs/pytorch1.9/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/cxt/miniconda3/envs/pytorch1.9/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/cxt/miniconda3/envs/pytorch1.9/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/cxt/miniconda3/envs/pytorch1.9/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/cxt/miniconda3/envs/pytorch1.9/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 27, in modify_and_download_model
    onnx_modifier.modify(modify_info)
  File "/Users/cxt/Reposities/onnx-modifier/onnx_modifier.py", line 302, in modify
    self.post_process()
  File "/Users/cxt/Reposities/onnx-modifier/onnx_modifier.py", line 278, in post_process
    shape_inference()
  File "/Users/cxt/Reposities/onnx-modifier/onnx_modifier.py", line 266, in shape_inference
    inferred_shape_info = onnx.shape_inference.infer_shapes(self.model_proto)
AttributeError: module 'onnx' has no attribute 'shape_inference'
```

**Comment by ZhangGe6** [comment]
谢谢反馈，请问使用的onnx版本是？

**Comment by XiaotaoChen** [comment]
onnx版本是1.6.0，python 3.6.13

**Comment by ZhangGe6** [comment]
好的get. 可以先试试`1.12.0`版本的onnx，看看能否正常使用。

我这边在安装onnx==1.6.0时会触发cmake编译，暂时没有成功，所以该issue的问题还没有复现。复现后会给反馈。

**Comment by XiaotaoChen** [comment]
我这边升级onnx到1.12.0版本后执行： `python app.py`报错如下所示, 这个版本的onnx是可以用onnx-modifer的，之前尝试过：
```shell
Traceback (most recent call last):
  File "app.py", line 4, in <module>
    from onnx_modifier import onnxModifier
  File "/Users/cxt/Reposities/onnx-modifier/onnx_modifier.py", line 11, in <module>
    import onnx
  File "/Users/cxt/miniconda3/envs/pytorch1.9/lib/python3.6/site-packages/onnx/__init__.py", line 5, in <module>
    from .onnx_cpp2py_export import ONNX_ML
ImportError: dlopen(/Users/cxt/miniconda3/envs/pytorch1.9/lib/python3.6/site-packages/onnx/onnx_cpp2py_export.cpython-36m-darwin.so, 0x0002): symbol not found in flat namespace '__ZN6google8protobuf11MessageLite20ParseFromCodedStreamEPNS0_2io16CodedInputStreamE'
```

**Comment by XiaotaoChen** [comment]
在新环境中使用onnx 1.12.0版本可以正常保持，没有问题

**Comment by ZhangGe6** [comment]
ok👌
