### ISSUE TITLE
Can not modify input / output sizes

### ISSUE THREAD

**Issue by piotrwierzba-tplx** [ZhangGe6/onnx-modifier#69]
While editing ONNX, one might remove nodes between output / input, which in turn affect the input / output shapes. 
Unfortunately, the input and output shapes cannot be modified in the editor. Checking the net using the following command:
```
>>> model = onnx.load("model.onnx")
>>> onnx.checker.check_model(model)
>>> onnx.checker.check_model(model, True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.11/site-packages/onnx/checker.py", line 108, in check_model
    onnx.shape_inference.infer_shapes(model, check_type=True, strict_mode=True)
  File "/opt/homebrew/lib/python3.11/site-packages/onnx/shape_inference.py", line 34, in infer_shapes
    inferred_model_str = C.infer_shapes(model_str, check_type, strict_mode, data_prop)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
onnx.onnx_cpp2py_export.shape_inference.InferenceError: [ShapeInferenceError] (op_type:Conv, node name: Conv18): [ShapeInferenceError] Inferred shape and existing shape differ in dimension 2: (357) vs (30)
```

Yields various errors, depending whether the input or the output have wrong shapes. Please add a way to either strip or modify the input / output shapes, as saving the modified network will not result in a correct model that can be used.

**Comment by ZhangGe6** [comment]
@piotrwierzba-tplx Thanks for reporting. It IS a problem that the current version cannot handle well. I am thinking about how to fix it. It is suggested to add some ONNX operators that can modify the input / output shape, such as `Reshape` and `Transpose`.

**Comment by KONGYOUYL** [comment]
> reporting

hello, there is some question in op reshape. I add the op before output that want to shape it from [1, 5, 640, 640] to [1,5,409600],but it failed, can you help me to solve this problem? wait for your reply. 
![image](https://github.com/ZhangGe6/onnx-modifier/assets/87186632/06259f1a-8048-4847-9dba-4a7b259fca31)
![image](https://github.com/ZhangGe6/onnx-modifier/assets/87186632/c32aca86-6e44-4c5f-b0dc-dc24dbf0df43)

**Comment by ZhangGe6** [comment]
@KONGYOUYL Hi, Sorry for the late response. Can you explain the failure with more info? It is suggested to share the error log in the console. Thanks.

**Comment by ZhangGe6** [comment]
Editing input shape is supported in [this commit](https://github.com/ZhangGe6/onnx-modifier/commit/85c143b4e55f8f72d7a4ab382c01145059700569). The Output sizes are not supposed to be changed manually and should rely on the result of shape inference. Please try the [shape inference](https://github.com/ZhangGe6/onnx-modifier?tab=readme-ov-file#usage) feature.
