### ISSUE TITLE
部分Attribute支持问题

### ISSUE THREAD

**Issue by wujiazong** [ZhangGe6/onnx-modifier#96]
我想往模型中加入一个resize操作,但是报错.
经过检查,发现resize需要的属性Attribute中存在string类型,报错如下:
```
Traceback (most recent call last):
  File "E:\project\Onnx_modify\onnx-modifier-master\venv\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\project\Onnx_modify\onnx-modifier-master\venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\project\Onnx_modify\onnx-modifier-master\venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\project\Onnx_modify\onnx-modifier-master\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "E:\project\Onnx_modify\onnx-modifier-master\app.py", line 37, in modify_and_download_onnx
    return modify_and_download_model_in_format('.onnx')
  File "E:\project\Onnx_modify\onnx-modifier-master\app.py", line 30, in modify_and_download_model_in_format
    onnx_modifier.modify(modify_info)
  File "E:\project\Onnx_modify\onnx-modifier-master\onnx_modifier.py", line 463, in modify
    self.add_nodes(modify_info['added_node_info'], modify_info['node_states'])
  File "E:\project\Onnx_modify\onnx-modifier-master\onnx_modifier.py", line 226, in add_nodes
    node = make_new_node(node_info)
  File "E:\project\Onnx_modify\onnx-modifier-master\utils\make_nodes.py", line 15, in make_new_node
    attributes[attr_name] = parse_str2val(attr_value, attr_type)
  File "E:\project\Onnx_modify\onnx-modifier-master\utils\parse_tools.py", line 102, in parse_str2val
    raise RuntimeError(f"type {val_type} is not considered in current version.\n" + \
RuntimeError: type string is not considered in current version.
Currently supported types are:
 - int, int32, int64, int[], int32[], int64[]
 - float, float32, float64 and float[], float32[], float64[].
```

**Comment by ZhangGe6** [comment]
@wujiazong 谢谢反馈。已更新代码尝试修复该问题，请拉取最新代码尝试一下，如果问题仍然存在，欢迎继续讨论~
